# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 name: Default
 demands:
   - Agent.Name -equals UP636306
 

steps:
# - script: echo Hello, BEROE world!
#   displayName: 'Run a one-line BEROE script'


- script: |
    echo ScanCentral version check.
    scancentral -version
  displayName: 'Run BEROE scancentral version check'

- task: FortifyScanCentralSAST@7
  inputs:
    scanCentralClientToken: '$(ScanCentral.ClientToken)'
    sscCiToken: '$(ScanCentral.SscCiToken)'
    buildTool: 'none'


